version: "3.9"

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=user
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit log_levels [{connection,error},{default,error}]
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./rabbitmq:/var/lib/rabbitmq

  postgres:
    container_name: postgresql
    image: b0b90c1d9579032974dc7a3914392004b29e31c071524575b45ee9985f1c43ba
    ports:
      - 5432:5432
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: MicroserviceCalculatorDB
    volumes:
      - ./db_data:/var/lib/postgresql/data

  orchestrator:
    container_name: orchestrator
    build: 
      context: .
      dockerfile: ./orchestrator/Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    depends_on:
      - rabbitmq
      - postgres
    command: sh -c "sleep 30 && goose -dir /app/migrations postgres 'postgres://admin:admin@postgres:5432/MicroserviceCalculatorDB' up && ./orchestratorExe"

  agent:
    container_name: agent
    build: 
      context: .
      dockerfile: ./agent/Dockerfile
    restart: unless-stopped
    depends_on:
      - orchestrator
