// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: expressions.sql

package database

import (
	"context"
	"database/sql"
)

const createExpression = `-- name: CreateExpression :one
INSERT INTO expressions (id, expression_body, expression_status_id, expression_result)
VALUES($1, $2, $3, $4)
RETURNING id, expression_body, expression_status_id, expression_result
`

type CreateExpressionParams struct {
	ID                 string
	ExpressionBody     string
	ExpressionStatusID int32
	ExpressionResult   sql.NullFloat64
}

func (q *Queries) CreateExpression(ctx context.Context, arg CreateExpressionParams) (Expression, error) {
	row := q.db.QueryRowContext(ctx, createExpression,
		arg.ID,
		arg.ExpressionBody,
		arg.ExpressionStatusID,
		arg.ExpressionResult,
	)
	var i Expression
	err := row.Scan(
		&i.ID,
		&i.ExpressionBody,
		&i.ExpressionStatusID,
		&i.ExpressionResult,
	)
	return i, err
}
