// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
)

type Expression struct {
	ID                 string
	ExpressionBody     string
	ExpressionStatusID int32
	ExpressionResult   sql.NullFloat64
}

type Status struct {
	ID         int32
	StatusName string
}

type Subexpression struct {
	ExpressionID          string
	SubexpressionNumber   int32
	SubexpressionBody     string
	SubexpressionStatusID int32
	SubexpressionResult   sql.NullFloat64
}
