// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: operators_durations.sql

package database

import (
	"context"
)

const getDurations = `-- name: GetDurations :many
SELECT operator_name, operator_duration FROM operators_durations
`

func (q *Queries) GetDurations(ctx context.Context) ([]OperatorsDuration, error) {
	rows, err := q.db.QueryContext(ctx, getDurations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []OperatorsDuration
	for rows.Next() {
		var i OperatorsDuration
		if err := rows.Scan(&i.OperatorName, &i.OperatorDuration); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
